name: Test Services

# The services other than the API (the API has test-api.yml)
on:
  pull_request:
    branches: ['master']
    paths: ['packages/ingest/**', 'packages/bot/**', 'packages/database/**', 'packages/utils/**']

jobs:
  test_service:
    strategy:
      fail-fast: false
      matrix:
        service: [ingest, bot]
    uses: ./.github/workflows/test-service.yml
    with:
      service: ${{ matrix.service }}
