name: Test API

on:
  pull_request:
    branches: ['master']
    paths: ['packages/api/**', 'packages/core/**']

jobs:
  test_api:
    uses: ./.github/workflows/test-service.yml
    with:
      service: api
